language: ruby
rvm:
  - 2.1.0
  - 2.1.5
  - 2.2.4
  - 2.3.0
before_install:
  - git submodule update --init --recursive --force
  - gem update bundler
before_script:
  #- go get github.com/FiloSottile/Heartbleed
  #- go install github.com/FiloSottile/Heartbleed
  #- which Heartbleed
  - sudo apt-get update
  - sudo apt-get install build-essential git libxml2 libxml2-dev
    libxslt-dev libcurl4-openssl-dev libsqlite3-dev libyaml-dev zlib1g-dev
    python-dev python-pip python-setuptools curl nmap w3af-console wget golang
  - export SSLYZE_PATH="/home/travis/build/gauntlt/gauntlt/vendor/sslyze/sslyze_cli.py"
  - export SQLMAP_PATH="/home/travis/build/gauntlt/gauntlt/vendor/sqlmap/sqlmap.py"
  - 'cd vendor/Garmr && sudo python setup.py install && cd ../..'
  - 'cd vendor && wget http://downloads.sourceforge.net/project/dirb/dirb/2.03/dirb203.tar.gz && tar xvfz dirb203.tar.gz && cd dirb && ./configure && make && sudo cp dirb /usr/local/bin/ && cd ..'
  - export DIRB_WORDLISTS="/home/travis/build/gauntlt/gauntlt/vendor/dirb/wordlists"
#notifications:
#  irc:
#    channels:
#      - "chat.freenode.net#gauntlt"
#    use_notice: true
